name: "编程语言统计"
on: [push, pull_request]
  # schedule: [{cron: "0 16 * * *"}]
  # workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_order: languages, notable, discussions, topics
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 1
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_discussions: yes
          output_action: write